services:
  feature_server:
    container_name: feature_server
    build:
      context: ./feature_repo
    volumes:
      - ./feature_repo:/app/feature_repo
      - ./feature_repo/offline_data:/app/offline_data  # ✅ Mounts `offline_data` directly inside `/app/`
    depends_on:
      registry:
        condition: service_healthy
      redis:
        condition: service_started
      dask-worker:
        condition: service_started
    ports:
      - "6566:6566"
    links:
      - registry
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:6566/health}"
      interval: "5s"
      retries: 5
    restart: unless-stopped

  kafka_consumer:
    build:
      context: ./streaming/kafka_consumer
    volumes:
      - ./feature_repo/offline_data:/app/offline_data # @BA needed by data_sources.traffic_light_batch_source: FileSource
    container_name: kafka_consumer
    depends_on:
      broker-1:
        condition: service_healthy
      feature_server:
        condition: service_healthy
      kafka_producer:
        condition: service_started
    environment:
      - KAFKA_BROKER=broker:9092
      - FEAST_REPO_PATH=/app/feature_repo
    restart: unless-stopped

  spark_ingestor:
    build:
      context: ./streaming/spark_processor
      dockerfile: ./Dockerfile
    volumes:
      - ./feature_repo/offline_data:/app/offline_data
    container_name: spark_ingestor
    depends_on:
      broker-1:
        condition: service_started
      feature_server:
        condition: service_healthy
      kafka_producer:
        condition: service_started
    restart: unless-stopped

  kafka_producer:
    build:
      context: streaming/kafka_producer
      dockerfile: ./Dockerfile
    container_name: kafka_producer
    depends_on:
      broker-1:
        condition: service_healthy
      feature_server:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=broker:9092
    volumes:
      - ./feature_repo/offline_data:/app/offline_data
    restart: unless-stopped

  registry:
    container_name: registry
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=feast
    ports:
      - "55001:5432"
    volumes:
      # Separate data and configuration volumes
      - ./feast-postgres-registry:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: unless-stopped

    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c listen_addresses='*'
      -c max_connections=200

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  dask-scheduler:
    image: ghcr.io/dask/dask:latest
    container_name: dask-scheduler
    command: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    restart: unless-stopped

  dask-worker:
    image: ghcr.io/dask/dask:latest
    container_name: dask-worker
    command: dask-worker dask-scheduler:8786
    depends_on:
      - dask-scheduler
    links:
      - dask-scheduler
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  broker-1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "broker-1:9092", "--list" ]
      interval: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped